# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
orbs:
  slack: circleci/slack@3.4.2
version: 2.1
jobs:
  npm:
    resource_class: small
    docker:
      - image: cimg/node:20.5
    environment:
      CI: false
      NODE_OPTIONS: --max-old-space-size=8012
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: install
          command: |
            npm install --force
      - run:
          name: build
          no_output_timeout: 30m
          command: |
            npm run build
workflows:
  version: 2
  build_and_test:
    jobs:
      - publish