export enum JobStatus {
  ENQUEUED = 'ENQUEUED',
  FAILED = 'FAILED',
  PROCESSING = 'PROCESSING',
  SCHEDULED = 'SCHEDULED',
  SUCCEEDED = 'SUCCEEDED',
  DELETED = 'DELETED',
  STOPPING = 'STOPPING',
  STOPPED = 'STOPPED',
  DEAD = 'DEAD',
}